# Configuração do Banco de Dados MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/managerTasks
spring.datasource.username=root
spring.datasource.password=changeit
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuração do Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=true

server.port=8081
